fps: 60
env_height: 900
env_width: 1000

initial_boids: 50
obstacle_radius: 20

boid_size: 10
boid_velocity: 5
fov_angle: 360
fov_radius: 50

algorithm_cfgs:
    boid_max_force: 0.5     # controls the maximum magnitude of the steering vector
    obstacle_factor: 1.0    # controls how fast reacts to an obstacle
    wall_factor: 3.5        # controls how fast reacts to a wall
    align_factor: 1.4       # controls how fast reacts to alignment
    cohesion_factor: 10.0   # controls how fast reacts to cohesion
    separation_factor: 12.0 # controls how fast reacts to separation

draw_fov: False
